/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csc4380jchackofinalproject;

import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.LayoutManager2;
import java.awt.event.ActionListener;
import javax.swing.BoxLayout;

/**
 *
 * @author admin
 */
public class viewFinalPersonalInformation extends javax.swing.JFrame {

    /**
     * Creates new form viewFinalPersonalInformation
     */
    public viewFinalPersonalInformation() {
        initComponents();
        myinitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlPersonal = new javax.swing.JPanel();
        dtpPersonalInfo = new javax.swing.JDesktopPane();
        pnlAdd = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblAddSuccess = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        pnlSearch = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblIdResults = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        lbNotFound = new javax.swing.JLabel();
        pnlPersonalInfo = new javax.swing.JPanel();
        lblname = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblNameResults = new javax.swing.JLabel();
        lblGenderResults = new javax.swing.JLabel();
        lblAgeResults = new javax.swing.JLabel();
        lblAddressResults = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        btnUpdateName = new javax.swing.JButton();
        btnUpdateGender = new javax.swing.JButton();
        btnUpdateAge = new javax.swing.JButton();
        btnUpdateAddress = new javax.swing.JButton();
        pnlFamily = new javax.swing.JPanel();
        dtpFamilyInfo = new javax.swing.JDesktopPane();
        pnlFamilyInfo = new javax.swing.JPanel();
        lblFatherName = new javax.swing.JLabel();
        lblMotherName = new javax.swing.JLabel();
        lblSiblings = new javax.swing.JLabel();
        lblPartnerName = new javax.swing.JLabel();
        lblChildren = new javax.swing.JLabel();
        lblFatherNameResult = new javax.swing.JLabel();
        lblMotherNameResult = new javax.swing.JLabel();
        lblSiblingNumberResult = new javax.swing.JLabel();
        lblPartnerNameResult = new javax.swing.JLabel();
        lblChildrenNumberResult = new javax.swing.JLabel();
        txtFather = new javax.swing.JTextField();
        txtMother = new javax.swing.JTextField();
        txtSiblings = new javax.swing.JTextField();
        txtPartner = new javax.swing.JTextField();
        txtChildren = new javax.swing.JTextField();
        btnUpdateFather = new javax.swing.JButton();
        btnUpdateMother = new javax.swing.JButton();
        btnUpdateSiblling = new javax.swing.JButton();
        btnUpdatePartner = new javax.swing.JButton();
        btnUpdateChildren = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        btnDefaultLayout = new javax.swing.JButton();
        btnLineLayout = new javax.swing.JButton();
        btnBackwardsLayout = new javax.swing.JButton();
        btnExperimentLayout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dtpPersonalInfo.setBackground(new java.awt.Color(200, 200, 200));

        jLabel1.setText("Add new person");

        lblAddSuccess.setText("lblAddSuccess");

        btnAdd.setText("Add");

        javax.swing.GroupLayout pnlAddLayout = new javax.swing.GroupLayout(pnlAdd);
        pnlAdd.setLayout(pnlAddLayout);
        pnlAddLayout.setHorizontalGroup(
            pnlAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnAdd)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlAddLayout.createSequentialGroup()
                .addComponent(lblAddSuccess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(271, 271, 271))
        );
        pnlAddLayout.setVerticalGroup(
            pnlAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddLayout.createSequentialGroup()
                .addGroup(pnlAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAddSuccess)
                .addGap(0, 75, Short.MAX_VALUE))
        );

        lblSearch.setText("Search by ID");

        lblId.setText("ID #");

        lblIdResults.setText("jLabel7");

        btnSearch.setText("Search");

        txtSearch.setMinimumSize(new java.awt.Dimension(59, 20));

        lbNotFound.setText("lbNotFound");

        javax.swing.GroupLayout pnlSearchLayout = new javax.swing.GroupLayout(pnlSearch);
        pnlSearch.setLayout(pnlSearchLayout);
        pnlSearchLayout.setHorizontalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNotFound, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSearchLayout.createSequentialGroup()
                            .addComponent(lblId)
                            .addGap(18, 18, 18)
                            .addComponent(lblIdResults)
                            .addGap(7, 7, 7))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSearchLayout.createSequentialGroup()
                            .addComponent(lblSearch)
                            .addGap(35, 35, 35)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnSearch)
                            .addContainerGap()))))
        );
        pnlSearchLayout.setVerticalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(lblIdResults))
                .addGap(7, 7, 7)
                .addGroup(pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearch)
                    .addComponent(btnSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNotFound)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblname.setText("Name");

        lblGender.setText("Gender");

        lblAge.setText("Age");

        lblAddress.setText("Address");

        lblNameResults.setText("jLabel6");

        lblGenderResults.setText("jLabel2");

        lblAgeResults.setText("jLabel7");

        lblAddressResults.setText("jLabel8");

        txtName.setMinimumSize(new java.awt.Dimension(59, 59));

        txtAge.setMaximumSize(new java.awt.Dimension(59, 59));
        txtAge.setMinimumSize(new java.awt.Dimension(59, 59));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        btnUpdateName.setText("Update");

        btnUpdateGender.setText("Update");

        btnUpdateAge.setText("Update");

        btnUpdateAddress.setText("Update");

        javax.swing.GroupLayout pnlPersonalInfoLayout = new javax.swing.GroupLayout(pnlPersonalInfo);
        pnlPersonalInfo.setLayout(pnlPersonalInfoLayout);
        pnlPersonalInfoLayout.setHorizontalGroup(
            pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                        .addComponent(lblAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAddressResults))
                    .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                        .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAgeResults))
                    .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                        .addComponent(lblGender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGenderResults))
                    .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                        .addComponent(lblname)
                        .addGap(53, 53, 53)
                        .addComponent(lblNameResults)))
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdateName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnUpdateGender, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnUpdateAge, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 708, Short.MAX_VALUE)
                        .addComponent(btnUpdateAddress)))
                .addContainerGap())
        );
        pnlPersonalInfoLayout.setVerticalGroup(
            pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonalInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname)
                    .addComponent(lblNameResults)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(lblGenderResults)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateGender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(lblAgeResults)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAddress)
                        .addComponent(lblAddressResults))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateAddress))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dtpPersonalInfoLayout = new javax.swing.GroupLayout(dtpPersonalInfo);
        dtpPersonalInfo.setLayout(dtpPersonalInfoLayout);
        dtpPersonalInfoLayout.setHorizontalGroup(
            dtpPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dtpPersonalInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dtpPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPersonalInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(dtpPersonalInfoLayout.createSequentialGroup()
                        .addComponent(pnlAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dtpPersonalInfoLayout.setVerticalGroup(
            dtpPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dtpPersonalInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dtpPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dtpPersonalInfoLayout.createSequentialGroup()
                        .addComponent(pnlAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 42, Short.MAX_VALUE))
                    .addComponent(pnlSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPersonalInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dtpPersonalInfo.setLayer(pnlAdd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dtpPersonalInfo.setLayer(pnlSearch, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dtpPersonalInfo.setLayer(pnlPersonalInfo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnlPersonalLayout = new javax.swing.GroupLayout(pnlPersonal);
        pnlPersonal.setLayout(pnlPersonalLayout);
        pnlPersonalLayout.setHorizontalGroup(
            pnlPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dtpPersonalInfo)
                .addContainerGap())
        );
        pnlPersonalLayout.setVerticalGroup(
            pnlPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dtpPersonalInfo)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Personal info", pnlPersonal);

        dtpFamilyInfo.setBackground(new java.awt.Color(200, 200, 200));

        lblFatherName.setText("Father's name");

        lblMotherName.setText("Mother's name");

        lblSiblings.setText("Number of siblings");

        lblPartnerName.setText("Partner's name");

        lblChildren.setText("Number of children");

        lblFatherNameResult.setText("jLabel1");

        lblMotherNameResult.setText("jLabel2");

        lblSiblingNumberResult.setText("jLabel3");

        lblPartnerNameResult.setText("jLabel4");

        lblChildrenNumberResult.setText("jLabel1");

        btnUpdateFather.setText("Update");

        btnUpdateMother.setText("Update");

        btnUpdateSiblling.setText("Update");

        btnUpdatePartner.setText("Update");

        btnUpdateChildren.setText("Update");

        javax.swing.GroupLayout pnlFamilyInfoLayout = new javax.swing.GroupLayout(pnlFamilyInfo);
        pnlFamilyInfo.setLayout(pnlFamilyInfoLayout);
        pnlFamilyInfoLayout.setHorizontalGroup(
            pnlFamilyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFamilyInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFamilyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFatherName)
                    .addComponent(lblMotherName)
                    .addComponent(lblSiblings)
                    .addComponent(lblPartnerName)
                    .addComponent(lblChildren))
                .addGap(22, 22, 22)
                .addGroup(pnlFamilyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFamilyInfoLayout.createSequentialGroup()
                        .addComponent(lblMotherNameResult)
                        .addGap(18, 18, 18)
                        .addComponent(txtMother, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdateMother))
                    .addGroup(pnlFamilyInfoLayout.createSequentialGroup()
                        .addComponent(lblFatherNameResult)
                        .addGap(18, 18, 18)
                        .addComponent(txtFather, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdateFather))
                    .addGroup(pnlFamilyInfoLayout.createSequentialGroup()
                        .addComponent(lblChildrenNumberResult)
                        .addGap(18, 18, 18)
                        .addComponent(txtChildren, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 864, Short.MAX_VALUE)
                        .addComponent(btnUpdateChildren))
                    .addGroup(pnlFamilyInfoLayout.createSequentialGroup()
                        .addComponent(lblSiblingNumberResult)
                        .addGap(18, 18, 18)
                        .addComponent(txtSiblings, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdateSiblling))
                    .addGroup(pnlFamilyInfoLayout.createSequentialGroup()
                        .addComponent(lblPartnerNameResult)
                        .addGap(18, 18, 18)
                        .addComponent(txtPartner, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdatePartner)))
                .addContainerGap())
        );
        pnlFamilyInfoLayout.setVerticalGroup(
            pnlFamilyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFamilyInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFamilyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFatherNameResult)
                    .addComponent(txtFather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateFather))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFamilyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMotherName)
                    .addComponent(lblMotherNameResult)
                    .addComponent(txtMother, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateMother))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFamilyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSiblings)
                    .addComponent(lblSiblingNumberResult)
                    .addComponent(txtSiblings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateSiblling))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFamilyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPartnerName)
                    .addComponent(lblPartnerNameResult)
                    .addComponent(txtPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdatePartner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFamilyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChildren)
                    .addComponent(lblChildrenNumberResult)
                    .addComponent(txtChildren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateChildren))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dtpFamilyInfoLayout = new javax.swing.GroupLayout(dtpFamilyInfo);
        dtpFamilyInfo.setLayout(dtpFamilyInfoLayout);
        dtpFamilyInfoLayout.setHorizontalGroup(
            dtpFamilyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dtpFamilyInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFamilyInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dtpFamilyInfoLayout.setVerticalGroup(
            dtpFamilyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dtpFamilyInfoLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(pnlFamilyInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        dtpFamilyInfo.setLayer(pnlFamilyInfo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnlFamilyLayout = new javax.swing.GroupLayout(pnlFamily);
        pnlFamily.setLayout(pnlFamilyLayout);
        pnlFamilyLayout.setHorizontalGroup(
            pnlFamilyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFamilyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dtpFamilyInfo)
                .addContainerGap())
        );
        pnlFamilyLayout.setVerticalGroup(
            pnlFamilyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFamilyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dtpFamilyInfo)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Family info", pnlFamily);

        jToolBar2.setBackground(new java.awt.Color(100, 100, 100));
        jToolBar2.setRollover(true);

        btnDefaultLayout.setText("Default Layout");
        btnDefaultLayout.setFocusable(false);
        btnDefaultLayout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDefaultLayout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnDefaultLayout);

        btnLineLayout.setText("Line");
        btnLineLayout.setFocusable(false);
        btnLineLayout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLineLayout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnLineLayout);

        btnBackwardsLayout.setText("Backwards");
        btnBackwardsLayout.setFocusable(false);
        btnBackwardsLayout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBackwardsLayout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnBackwardsLayout);

        btnExperimentLayout.setText("Corner");
        btnExperimentLayout.setFocusable(false);
        btnExperimentLayout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExperimentLayout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnExperimentLayout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myinitComponents(){
        this.setTitle("Jervine Chacko Final Project");
        txtGender.setEditable(true);
        
        //Clears Add Success and notfound label at start of program
        lblAddSuccess.setText("");
        lbNotFound.setText("");
        this.setLocationRelativeTo(null);
        
        
        lmA = (LayoutManager2) dtpPersonalInfo.getLayout();
        lmB = (LayoutManager2) dtpFamilyInfo.getLayout();
        
        bxlA = new BoxLayout(dtpPersonalInfo, BoxLayout.X_AXIS);
        bxlB = new BoxLayout(dtpFamilyInfo, BoxLayout.X_AXIS);
        
        bxlA.addLayoutComponent(pnlAdd, BoxLayout.X_AXIS);
        bxlA.addLayoutComponent(pnlSearch, BoxLayout.X_AXIS);
        bxlA.addLayoutComponent(pnlPersonalInfo, BoxLayout.X_AXIS);
        
        bxlB.addLayoutComponent(pnlFamilyInfo, BoxLayout.X_AXIS);
        
        blA = new BorderLayout();
        blB = new BorderLayout();
        
        blA.addLayoutComponent(pnlPersonalInfo, BorderLayout.NORTH);
        blA.addLayoutComponent(pnlSearch, BorderLayout.WEST);
        blA.addLayoutComponent(pnlAdd, BorderLayout.EAST);
        
        blB.addLayoutComponent(pnlFamilyInfo, BorderLayout.NORTH);
        
        gblA = new GridBagLayout();
        gblB = new GridBagLayout();
        GridBagConstraints gcA = new GridBagConstraints();
        GridBagConstraints gcB = new GridBagConstraints();
        
        
        
        gcA.weightx = 10;
        gcA.weighty = 10;
        
        gcA.gridx = 0;
        gcA.gridy = 0;
        gblA.addLayoutComponent(dtpPersonalInfo, gcA);
        
        
        gcA.gridx = 2;
        gcA.gridy = 0;
        gblA.addLayoutComponent(pnlSearch, gcA);
        gcA.gridx = 2;
        gcA.gridy = 1;
        gblA.addLayoutComponent(pnlFamilyInfo, gcA);
        gcA.gridx = 3;
        gcA.gridy = 5;
        gblA.addLayoutComponent(pnlAdd, gcA);
        
        gcB.weightx = 10;
        gcB.weighty = 10;
        gcB.gridx = 0;
        gcB.gridy = 0;
        gblB.addLayoutComponent(dtpFamilyInfo, gcB);  
        gcB.gridx = 2;
        gcB.gridy = 0;
        gblB.addLayoutComponent(pnlFamilyInfo, gcB);
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewFinalPersonalInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewFinalPersonalInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewFinalPersonalInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewFinalPersonalInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewFinalPersonalInformation().setVisible(true);
            }
        });
    }
    
    
    
    
    /*******  Set Layout Methods  ********/
    void setDefaultLayout(){
        dtpPersonalInfo.setLayout(lmA);
        dtpFamilyInfo.setLayout(lmB);
        this.revalidate();
        this.repaint();
    }
    void setLineLayout(){
        dtpPersonalInfo.setLayout(bxlA);
        dtpFamilyInfo.setLayout(bxlB);
        this.revalidate();
        this.repaint();
    }
    void setBackwardsLayout(){
        dtpPersonalInfo.setLayout(blA);
        dtpFamilyInfo.setLayout(blB);
        this.revalidate();
        this.repaint();
    }
    void setExperimentLayout(){
        dtpPersonalInfo.setLayout(gblA);
        dtpFamilyInfo.setLayout(gblB);
        this.revalidate();
        this.repaint();
    }
    
    
    
    
    /****************Set Methods**********************/
    //These set the values for each label passed from controller
    void setIdResults(int intId){
        lblIdResults.setText(Integer.toString(intId));
        
    }
    
    void setNameResults(String strName){
        lblNameResults.setText(strName);
        
    }
    
    void setGenderResults(String strGender){
        lblGenderResults.setText(strGender);
        

    }
    void setAgeResults(int intAge){
        lblAgeResults.setText(Integer.toString(intAge));
        
    }
    void setAddressResults(String strAddress){
        lblAddressResults.setText(strAddress);
        
    }
    void setFatherResults(String strFatherName){
        lblFatherNameResult.setText(strFatherName);
        
    }
    void setMotherResults(String strMotherName){
        lblMotherNameResult.setText(strMotherName);
        
    }
    void setSiblingResults(int intSiblingNumber){
        lblSiblingNumberResult.setText(Integer.toString(intSiblingNumber));
        
    }
    void setPartnerResults(String strPartnerName){
        lblPartnerNameResult.setText(strPartnerName);
        
    }
    void setChildrenResults(int intChildrenNumber){
        lblChildrenNumberResult.setText(Integer.toString(intChildrenNumber));
        
    }
    
    
    void setAddSuccess(String strAddSuccess){
        lblAddSuccess.setText(strAddSuccess);
    }
    void setNotFound(Boolean boolNotFound){
        if(boolNotFound){
            lbNotFound.setText("Error ID Not found");
        }
        else{
            lbNotFound.setText("");
        }
    }
    
    
    /********************* UPDATE BUTTONS******************************/
    //they get the text values from the textfields and returns them and clears textfield
    int getUpdateId(){
        intFindId = Integer.parseInt(txtSearch.getText());
        txtSearch.setText("");
        return intFindId;
    }
    String  getUpdateName(){
        strFindName = txtName.getText();
        txtName.setText("");
        lblNameResults.setText(strFindName);
        return strFindName;
    }
    String  getUpdateGender(){
        strFindGender = txtGender.getText();
        txtGender.setText("");
        lblGenderResults.setText(strFindGender);
        return strFindGender;
    }
    int  getUpdateAge(){
        intFindAge = Integer.parseInt(txtAge.getText());
        txtAge.setText("");
        lblAgeResults.setText(Integer.toString(intFindAge));
        return intFindAge;
    }
    String  getUpdateAddress(){
        strFindAddress = txtAddress.getText();
        txtAddress.setText("");
        lblAddressResults.setText(strFindAddress);
        return strFindAddress;
    }
    String  getUpdateFather(){
        strFindFatherName = txtFather.getText();
        txtFather.setText("");
        lblFatherNameResult.setText(strFindFatherName);
        return strFindFatherName;
    }
    String  getUpdateMother(){
        strFindMotherName = txtMother.getText();
        txtMother.setText("");
        lblMotherNameResult.setText(strFindMotherName);
        return strFindMotherName;
    }
    int  getUpdateSibling(){
        intFindSiblingNumber = Integer.parseInt(txtSiblings.getText());
        txtSiblings.setText("");
        lblSiblingNumberResult.setText(Integer.toString(intFindSiblingNumber));
        return intFindSiblingNumber;
    }
    String  getUpdatePartner(){
        strFindPartnerName = txtPartner.getText();
        txtPartner.setText("");
        lblPartnerNameResult.setText(strFindPartnerName);
        return strFindPartnerName;
    }
    int  getUpdateChildren(){
        intFindChildrenNumber = Integer.parseInt(txtChildren.getText());
        txtChildren.setText("");
        lblChildrenNumberResult.setText(Integer.toString(intFindChildrenNumber));
        return intFindChildrenNumber;
    }
    
    
    
    
    
    
    /*************            Setting Action Listeners                    *************/
    void addUpdateNameListener(ActionListener evt){
        btnUpdateName.addActionListener(evt);
    }
    void addUpdateGenderListener(ActionListener evt){
        btnUpdateGender.addActionListener(evt); 
    }
    void addUpdateAgeListener(ActionListener evt){
        btnUpdateAge.addActionListener(evt);    
    }
    void addUpdateAddressListener(ActionListener evt){
        btnUpdateAddress.addActionListener(evt);
    }
    void addUpdateFatherListener(ActionListener evt){
        btnUpdateFather.addActionListener(evt);
    }
    void addUpdateMotherListener(ActionListener evt){
        btnUpdateMother.addActionListener(evt);
    }
    void addUpdateSiblingListener(ActionListener evt){
        btnUpdateSiblling.addActionListener(evt);
    }
    void addUpdatePartnerListener(ActionListener evt){
        btnUpdatePartner.addActionListener(evt);
    }
    void addUpdateChildrenListener(ActionListener evt){
        btnUpdateChildren.addActionListener(evt);
    }
    void addNewPersonListener(ActionListener evt){
        btnAdd.addActionListener(evt);
    }
    void addSearchListener(ActionListener evt){
        btnSearch.addActionListener(evt);
    }
    
    
    /***********  Layout Buttons  *************/
    void addDefaultLayoutListener(ActionListener evt){
        btnDefaultLayout.addActionListener(evt);
    }
    void addLineLayoutListener(ActionListener evt){
        btnLineLayout.addActionListener(evt);
    }
    void addBackwardsLayoutListener(ActionListener evt){
        btnBackwardsLayout.addActionListener(evt);
    }
    void addExperimentLayoutListener(ActionListener evt){
        btnExperimentLayout.addActionListener(evt);
    }
    
    
        int intFindId;
        String strFindName;
        String strFindGender;
        int intFindAge;
        String strFindAddress;
        String strFindFatherName;
        String strFindMotherName;
        int intFindSiblingNumber;
        String strFindPartnerName;
        int intFindChildrenNumber;
        
        LayoutManager2 lmA;
        LayoutManager2 lmB;
        
        BoxLayout bxlA;
        BoxLayout bxlB;
        
        BorderLayout blA;
        BorderLayout blB;
        GridBagLayout gblA;
        GridBagLayout gblB;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBackwardsLayout;
    private javax.swing.JButton btnDefaultLayout;
    private javax.swing.JButton btnExperimentLayout;
    private javax.swing.JButton btnLineLayout;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdateAddress;
    private javax.swing.JButton btnUpdateAge;
    private javax.swing.JButton btnUpdateChildren;
    private javax.swing.JButton btnUpdateFather;
    private javax.swing.JButton btnUpdateGender;
    private javax.swing.JButton btnUpdateMother;
    private javax.swing.JButton btnUpdateName;
    private javax.swing.JButton btnUpdatePartner;
    private javax.swing.JButton btnUpdateSiblling;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JDesktopPane dtpFamilyInfo;
    private javax.swing.JDesktopPane dtpPersonalInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel lbNotFound;
    private javax.swing.JLabel lblAddSuccess;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddressResults;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAgeResults;
    private javax.swing.JLabel lblChildren;
    private javax.swing.JLabel lblChildrenNumberResult;
    private javax.swing.JLabel lblFatherName;
    private javax.swing.JLabel lblFatherNameResult;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGenderResults;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdResults;
    private javax.swing.JLabel lblMotherName;
    private javax.swing.JLabel lblMotherNameResult;
    private javax.swing.JLabel lblNameResults;
    private javax.swing.JLabel lblPartnerName;
    private javax.swing.JLabel lblPartnerNameResult;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSiblingNumberResult;
    private javax.swing.JLabel lblSiblings;
    private javax.swing.JLabel lblname;
    private javax.swing.JPanel pnlAdd;
    private javax.swing.JPanel pnlFamily;
    private javax.swing.JPanel pnlFamilyInfo;
    private javax.swing.JPanel pnlPersonal;
    private javax.swing.JPanel pnlPersonalInfo;
    private javax.swing.JPanel pnlSearch;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtChildren;
    private javax.swing.JTextField txtFather;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtMother;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPartner;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSiblings;
    // End of variables declaration//GEN-END:variables
}
